language: java
install: true

jdk:
  - openjdk17

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - mvn verify

before_deploy:
  - io.opencaesar.rosetta.product/setversion.sh

deploy:
  - provider: script
    script: io.opencaesar.rosetta.repository/deploy.sh
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      branch: master
  - provider: releases
    api_key:
      secure: "D9DDV50RX0LONWBR+95zlOm1d1ui6wNLPfop6xu2EjILjwglX+i8RFUdFuNBm3SF6iA6tyG4hrH8PdYALi/zYvpOAVnLuJ4BQuudG/uVg2gPHJkhng9s5vtvgEtkqtc+z3WNHW3rkJA1gfv2KaPFEgrV5Tp9JMuqUtMWYL7j0VjiIK9QH4FfE+sS53drHyT4yEuSU4y0NGOGHrpXAHirq6RjFa5kvDWibW0zPdPnCEjBZRtSOQPt3IZmvXi8U7/gF/oPGXlxnoI0q+gkW58VpJ14l1qZ2EqFqj75cAOv6JLwf7/RU9MCIchcei9Yx2VNsuonXBgj0ajLz5bnhcvvB827jsMNjMoRD+i3TKreSNYIBA3nAKkbKTTyCUwSG22rseL0JOEmj/0pPQ0O25mt1h+hCg5H98RW813aVSbp7St0aid4nCpJcRtTa/gZSIdB3Voy4MuU5XQsFFGh3d6cj/7rbksAA1l7sl0X06me7WbaU8shZ4VE3K4mL1QZNsxF6eI88qujoPv8VsVfSzGpwtBFrmaAkc5Of3KV1ZjKeGGIzeC1QoCk2C2Bu/riRAg9PtFBe3wI0dGMEzXiipfnp+XpPohvHTSmfF7oLVb0Kk164ZOpldi6Ft03kdfDplxJ/2N7eZJ/j7ddyDbJQ35GKwUhLNlJXvredmgS0LMBpcM="
    file_glob: true
    file: io.opencaesar.rosetta.product/target/products/*
    skip_cleanup: true
    on:
      tags: true
      branch: master
