language: java
install: true

jdk:
  - openjdk11

sudo: false

cache:
  directories:
    - $HOME/.m2

before_script:
  - cd io.opencaesar.rosetta.parent

script:
  - mvn verify

deploy:
  - provider: script
    script: io.opencaesar.rosetta.repository/deploy.sh
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      branch: master
  - provider: script
    script: io.opencaesar.rosetta.product/deploy.sh
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      branch: master