name: Build p2 and OS artifacts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # ** means all branches and tags
  push:
    branches: "**"
  pull_request:
    branches: "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment variable 
    env:
      PRODUCTS_PATH: io.opencaesar.rosetta.product/target/products/rosetta
      LATEST_TAG: git describe --tags --abbrev=0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Java 
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          # https://github.com/actions/setup-java#supported-distributions
          distribution: 'temurin'
        
        # --batch-modes and --update-snapshots
      - run: mvn -B -U verify
      - run: $GITHUB_WORKSPACE/setversion.sh ${{ env.LATEST_TAG }}
      - run: mkdir staging && cp ${{ env.PRODUCTS_PATH }}/* staging 
      - uses: actions/upload-artifact@v3
        with: 
          name: Package
          path: staging