name: CD

on:
  release:
    types: [published]
      
jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Setup Git User
      run: |
        git config --global user.email "melaasar@gmail.com"
        git config --global user.name "Maged Elaasar"

    - name: Publish repository
      run: mvn deploy -Prelease-composite -Dgithub-update-repo=https://x-access-token:${ACTIONS_TOKEN}@github.com/opencaesar/oml-rosetta-p2
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

    #- name: Set Version
    #  run: io.opencaesar.rosetta.product/setversion.sh
